### ISSUE TITLE
escape { and } from first post changes

### ISSUE THREAD

**Issue by Mikkdrasil** [Mikkdrasil/la_searcher_bot#10]
user-types symbols { and } breaks the logic, when eval() happens.
so solution can be to escape these signs (like "\{", "\}") or to switch to json formatting in change_log instead of str(dict()).

example of the breaking user_input: 
select new_value from change_log where id=201436;

**Comment by AKagitin** [comment]
I suggest to use this str.translate() - see [Method 2 : Using String Translate Table](https://www.scaler.com/topics/escape-string-python/#:~:text=Method%202%20%3A%20Using%20String%20Translate%20Table) 
But I don't understand where to implement. May be in _def prettify_content(content)_?
What side effects of this escaping may occur?

**Comment by Mikkdrasil** [comment]
it's the case only for the script "identify_updates_of_the_first_post":

there's a function which saves the problematic content into PSQL:
save_new_record_into_change_log(conn, search_id, message_on_first_posts_diff,
                                                                'topic_first_post_change', 8)
                                                                
"problematic content" – is "message_on_first_posts_diff"
it is formed by function "process_first_page_comparison"
inside there's more specialized function – "clean_up_content"
and here i think we need to incorporate this "escape" to get rid of { and } in first post texts

regrading a method how to attack this problem – it could be either translate or replace or re.sub – up to you, i don't think there's a big difference b/w these methods for our case.

**Comment by Mikkdrasil** [comment]
merged. i'm completing the issue. 
we'd need to check if there will no errors with { and } in the upcoming month. if there will be any bugs – we'll reopen the task or create a new on.
thank you @AKagitin !
