### ISSUE TITLE
Exclude redundant notifications when inforg comments a search topic on the forum

### ISSUE THREAD

**Issue by AKagitin** [Mikkdrasil/la_searcher_bot#12]
We can reduce numer of notification messages in this case and send 1 instead of 2.
If we register notification of "Сообщение от Инфорг" type then we should not add notification "Новые комментарии по поиску" for the same text and time of the forum comment.

![image](https://github.com/Mikkdrasil/la_searcher_bot/assets/125404370/901160a6-637c-4bd9-a4f3-29e2c7b55920)

**Comment by AKagitin** [comment]
What is purpose of function ‎compose_com_msg_on_inforg_comments? If it adds 'Сообщение от' only for inforg's comments then imho it is redundant because inforg's comments allready composed as comments (see example above).
Or may be compose_com_msg_on_inforg_comments is necessary then it would be better to suppress the comments from inforg.
What if not to add new comments to New Records when type_of_comments == 'inforg'?  
(see [def enrich_new_records_with_comments](https://github.com/AKagitin/la_searcher_bot_ak/blob/db374d28d9ec5f5f1b43c1fdb4b7ccc0c9f89bb9/src/compose_notifications/main.py#L547C5-L547C37))

**Comment by AKagitin** [comment]
I suggest to disable sending 'Сообщение от ...'(change_type == 4) notification to user which is also subscribed to 'Новые комментарии по поиску' (change_type == 3).
To do this we should reduce list_of_users  that is composed in this line: https://github.com/Mikkdrasil/la_searcher_bot/blob/d31238673ce598d4fa1c5d553f160f1dd077bf96/src/compose_notifications/main.py#L2030.
After list_of_users  firstly composed we should check if new_record's change_type is 4.
In this case we should compose another list, let's name it change_type_3_list_of_users, by call of compose_users_list_from_users function against a new_record with change_type==3.
Then we can exclude users of change_type_3_list_of_users from list_of_users.

**Comment by Mikkdrasil** [comment]
> We can reduce numer of notification messages in this case and send 1 instead of 2. If we register notification of "Сообщение от Инфорг" type then we should not add notification "Новые комментарии по поиску" for the same text and time of the forum comment.
> 
> ![image](https://private-user-images.githubusercontent.com/125404370/252131591-901160a6-637c-4bd9-a4f3-29e2c7b55920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODI4ODQsIm5iZiI6MTcwNTQ4MjU4NCwicGF0aCI6Ii8xMjU0MDQzNzAvMjUyMTMxNTkxLTkwMTE2MGE2LTYzN2MtNGJkOS1hNGYzLTI5ZTJjN2I1NTkyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwOTA5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmZlYTVjZDljMDQ2OTA3NjMwNTVlMTM1YjI2ZTI0MTFkYzBmYWFjMTAyMzBkNTZjZTUyMTgwYWI2NjUwODYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7LrpcsdFz4HwnJ690jvRTY64_cTZDLO51rWJmJjFp0I)

indeed, these two types of messages should be "either one, or another" and should not be sent simultaneously. I thought I made this "restriction" (only one or another) more than a year ago. If the example in the screenshots – is an actual and recents, then yes, seems the current code works not how it was expected and it worth to fix it. I believe the additional fix should not be time-consuming, the whole mechanism for these two types of messages alrest exists.

**Comment by Mikkdrasil** [comment]
> compose_com_msg_on_inforg_comments

There are two "levels" for functions which compose text of messages: "commom" and "individual".
1. "common" – it is a stage of preparation of the text, which is the same for all users
2. "individual" – is a stage when the common message is enriched with individual data for specific user (like distance, if needed)

so, the function "compose_com_msg_on_inforg_comments" creates the parts of the message, which are common-for-all-users (this type of message does not have an "individual" part, so "common" message – is universal to all users)

> it adds 'Сообщение от' only for inforg's comments
right

why this type of notification was developed - because majority of users want to see only inforg's comments (filtered) and not all the comments. so, this type was introduced with a slightly changed wording (vs "all comments")

> What if not to add new comments to New Records when type_of_comments == 'inforg'?
the current logic of how user can choose notification type related to comments:
1. all (incl Inforg)
2. only inforg

theoretically, we can split it in another way:
1. all non-inforg comments
2. inforg comments

it's also okay – not sure it'll be more useful for users, but we can do it

**Comment by Mikkdrasil** [comment]
btw, the current implementation of "filtering" of Inform comments is done in lines 1390-1413 in function _crop_user_list_:
 
 `# FIXME -------- INFORG 2x -------------
        # 1. INFORG 2X notifications. crop the list of users, excluding Users who receives all types of notifications
        # (otherwise it will be doubling for them)
        try:
            temp_user_list = []
            if record.change_type != 4:
                for user_line in users_list_outcome:
                    # if this record is about inforg_comments and user already subscribed to all comments
                    if not user_line.all_notifs:
                        temp_user_list.append(user_line)
                        logging.info(f'Inforg 2x CHECK for {user_line.user_id} is OK, record {record.change_type}, '
                                     f'user {user_line.user_id} {user_line.all_notifs}. '
                                     f'record {record.forum_search_num}')
                    else:
                        logging.info(f'Inforg 2x CHECK for {user_line.user_id} is FAILED, record {record.change_type}, '
                                     f'user {user_line.user_id} {user_line.all_notifs}. '
                                     f'record {record.forum_search_num}')

            logging.info(f'User List crop due to Inforg 2x [DEMO]: {len(users_list_outcome)} --> {len(temp_user_list)}')
            # users_list_outcome = temp_user_list

        except Exception as e:
            logging.info(f'TEMP - exception CROP Inforg 2X: {repr(e)}')
        # FIXME ^^^ ----------------------`
        
       i suspect we just need to uncomment `# users_list_outcome = temp_user_list` and that's it. Probably i've commented it a time ago and forgot to uncomment

**Comment by Mikkdrasil** [comment]
i guess it does the same as you proposed

**Comment by Mikkdrasil** [comment]
i checked the mechanism of "filtering" works fine, but just disabled. below are log records for "inforg filtering" which IS NOT HAPPENING, but expected to happen if we uncomment
![Uploading image.png…]()

**Comment by AKagitin** [comment]
Could you please re-check the modification. 
1. Where crop_user_list is called from? I see only one place where this function is called by itself recoursively.
https://github.com/Mikkdrasil/la_searcher_bot/blob/4a69ccc5535d694a47fa2ba76275d2a9c752d367/src/compose_notifications/main.py#L1521
2. Here (https://github.com/Mikkdrasil/la_searcher_bot/blob/4a69ccc5535d694a47fa2ba76275d2a9c752d367/src/compose_notifications/main.py#L1393) users_list_outcome is cropped via temp_user_list to exclude users who are subscribed to all change_types. And this cropping occurs only if record.change_type != 4. I thought that we should exclude users who have subscription to any comments (change_type == 3) and not user_line.all_notifs if current record.change_type == 4 (inforg's comments).
3. Also I wonder what is effect of [# 4. DOUBLING. crop the list of users, excluding Users who were already notified on this change_log_id](https://github.com/Mikkdrasil/la_searcher_bot/blob/4a69ccc5535d694a47fa2ba76275d2a9c752d367/src/compose_notifications/main.py#L1486C9-L1486C111). But i think that it has no effect for this task if this item was active earlier when we saw the doubling of notifications from inforg.

**Comment by Mikkdrasil** [comment]
> 1. Where crop_user_list is called from? I see only one place where this function is called by itself recoursively

why you say "recursively"? it's called once per every "compose_notifications" script run. There's only one use of this function:
`list_of_users = crop_user_list(list_of_users, users_who_should_not_be_informed, new_record)`
So it does update the parameter "list_of_users" it gets, but there's no recursion, it's just an update of the "list_of_users". So your question is not yet clear for me, to be honest

**Comment by AKagitin** [comment]
What's about p.2 and 3 of my comment above?

**Comment by Mikkdrasil** [comment]
as for 
> 2. users_list_outcome is cropped via temp_user_list to exclude users who are subscribed to all change_types

i was cracking my head.. and seems you are right.

here's my vision on what is wrong:
<img width="389" alt="image" src="https://github.com/Mikkdrasil/la_searcher_bot/assets/79911692/2536e4c6-c68c-4f3f-bef6-73676f544f4d">

**Comment by Mikkdrasil** [comment]
so we need to change the code for "Inforg 2x crop" as follows:

```temp_user_list = []
        if record.change_type != 4:
            logging.info(f'User List crop due to Inforg 2x: {len(users_list_outcome)} --> {len(users_list_outcome)}')
        else:
            for user_line in users_list_outcome:
                # if this record is about inforg_comments and user already subscribed to all comments
                if not user_line.all_notifs:
                    temp_user_list.append(user_line)
                    logging.info(f'Inforg 2x CHECK for {user_line.user_id} is OK, record {record.change_type}, '
                                 f'user {user_line.user_id} {user_line.all_notifs}. '
                                 f'record {record.forum_search_num}')
                else:
                    logging.info(f'Inforg 2x CHECK for {user_line.user_id} is FAILED, record {record.change_type}, '
                                 f'user {user_line.user_id} {user_line.all_notifs}. '
                                 f'record {record.forum_search_num}')
            logging.info(f'User List crop due to Inforg 2x: {len(users_list_outcome)} --> {len(temp_user_list)}')
            users_list_outcome = temp_user_list```
        
        do you agree?

**Comment by Mikkdrasil** [comment]
> 3. But i think that it has no effect for this task if this item was active earlier when we saw the doubling of notifications from inforg.

the idea of this one – is a "safety net" or "double-check" that we haven't notified the same used with same notification twice. It happens rather often, but it happens: some of the scripts fail and re-run, so it can cause composing/sending the same message to same people several times. This code prevents exactly such cases.
so i would conclude it's needed and works fine in such critical situations

**Comment by AKagitin** [comment]
> so we need to change the code for "Inforg 2x crop" as follows:
I'd suggest that this block of code should be as follows:
`        if record.change_type != 4: ## 4==topic_inforg_comment_new
            logging.info(f'User List crop due to Inforg 2x: {len(users_list_outcome)} --> {len(users_list_outcome)}')
        else:# if this record is about inforg_comments
            for user_line in users_list_outcome:
                # append only if user is not subscribed to all_notifs and is not suscribed to topic_comment_new (all comments)
                if not user_line.all_notifs and not user_line.topic_comment_new:
                    temp_user_list.append(user_line)
                    logging.info(f'Inforg 2x CHECK for {user_line.user_id} is OK, record {record.change_type}, '
                                 f'user {user_line.user_id} {user_line.all_notifs}. '
                                 f'record {record.forum_search_num}')
                else:
                    logging.info(f'Inforg 2x CHECK for {user_line.user_id} is FAILED, record {record.change_type}, '
                                 f'user {user_line.user_id} {user_line.all_notifs}. '
                                 f'record {record.forum_search_num}')
            logging.info(f'User List crop due to Inforg 2x: {len(users_list_outcome)} --> {len(temp_user_list)}')
            users_list_outcome = temp_user_list`

To have **user_line.topic_comment_new** attribute we should modify here:
https://github.com/Mikkdrasil/la_searcher_bot/blob/4a69ccc5535d694a47fa2ba76275d2a9c752d367/src/compose_notifications/main.py#L1079
as follows:
`                            user_role=line[4], user_in_multi_folders=line[6], all_notifs=line[7], topic_comment_new=line[8])`

and here:
https://github.com/Mikkdrasil/la_searcher_bot/blob/4a69ccc5535d694a47fa2ba76275d2a9c752d367/src/compose_notifications/main.py#L1060
as follows:
`                    st.num_of_new_search_notifs, ns.multi_folder, ns.all_notifs, ns.topic_comment_new`

and here:
https://github.com/Mikkdrasil/la_searcher_bot/blob/4a69ccc5535d694a47fa2ba76275d2a9c752d367/src/compose_notifications/main.py#L1020
user_notif_type_pref should be as follows:
`                    user_notif_type_pref AS (
                        SELECT user_id, CASE WHEN 30 = ANY(agg) THEN True ELSE False END AS all_notifs 
						, CASE WHEN 3 = ANY(agg) THEN True ELSE False END AS topic_comment_new
                        FROM user_notif_pref_prep 
                        WHERE 30 = ANY(agg) OR 3 = ANY(agg) OR :a = ANY(agg)), /*30=all, 3=topic_comment_new*/    
`

**Comment by Mikkdrasil** [comment]
please suggest why you propose this change, as there's no more doubling between "all comments" and "inforg comments" any more?) 

> if not user_line.all_notifs and not user_line.topic_comment_new:
if i understand you – you propose to change the way how "all comments" are processed.
as i said before – we can do it, but this change concerns  more considerations:
1. "all comments" should be treated straight-forward, so if it's not "all" – we need to think how to call it
2. in my vision the setting "all comments" should be "equal" for all users – in order to give transparency and understanding what it is.
3. when user chooses/changes this setting in the "communicate" script - we need to work with the logic of how these settings are processed.

to be honests, all-in-all, i'm not convinced we'd need to focus on it right now – as far as the "problem of doubling all_comments and inforg_comments" does not  exist anymore. As i see it. Please suggest if i'm wrong here. Thanks!

**Comment by AKagitin** [comment]
I coud not understand why current version is working properly.
But it's OK.
