### ISSUE TITLE
Add functionality to link telegram user to forum user (to all users)

### ISSUE THREAD

**Issue by Mikkdrasil** [Mikkdrasil/la_searcher_bot#6]
Goal – is to give an opportunity to users to link their bot accounts to their forum accounts (at forum.lizaalert.org). This feature is required to unlock further features: like auto-identification that user is on a specific search, auto posting on user's behalf like (Стоп принял) etc.

Functionality of accounts "linkage" is developed already. If you send a text to bot "связать аккаунты бота и форума" – it will activate this functionality.
This feature is now available on the stage of Onboarding (several steps for setting up bot for a new user) and not available for any "old" users.

The goal – is to add access to this function for "old" users: when you are in the bot, there's a menu item "настроить бот". Once you click it – there's a list of available settings. We'd need to add this "связать аккаунты бота и форума" into the list. It definitely should be before the "back" button, but the "place" in the list of settings' buttons – up to you. 

We also need to check where user is "landed" (which buttons are given) once this process of "linkage" is finished. Mike believes that in both cases user should receive a universal "main buttons"(same as you will receive when push "в начало"). 

Once it's done – we'd need to check that behaviour for this functionality during Onboarding and during "regular" work is right for both cases (that it does not break Onboarding flow and it does not break regular settings update). How to check it – we can check logs and user-to-bot dialogs to assure that everything works smoothly.

**Comment by AKagitin** [comment]
As I understand it is enough to add b_set_forum_nick to keyboard_settings 
at line 2349 in la_searcher_bot/src/communicate/main.py.
Is it correct?

[la_searcher_bot](https://github.com/Mikkdrasil/la_searcher_bot/tree/e84f86ba6ba8b2d3cc70dab83d041127875871bd)/[src](https://github.com/Mikkdrasil/la_searcher_bot/tree/e84f86ba6ba8b2d3cc70dab83d041127875871bd/src)/[communicate](https://github.com/Mikkdrasil/la_searcher_bot/tree/e84f86ba6ba8b2d3cc70dab83d041127875871bd/src/communicate)
/main.py

**Comment by Mikkdrasil** [comment]
@AKagitin , i would say: 
- a "minimum objective" – yes, just to add this button
- a "maximum objective" – is to add more user-friendly functionality: modifying the message "Бот сможет быть еще полезнее, эффективнее" for the cases when there's a link already saying something like "Ваш аккакунт уже связан с пользователем форма с ником {forum_nickname}....".  This scenario will require checking the existing link once the button "b_set_forum_nick" is pushed.

**Comment by AKagitin** [comment]
I see that tokens b_yes_its_me and b_no_its_not_me are processed in manage_linking_to_forum but don't see where they come from (in which cases such token is put to got_message).

**Comment by AKagitin** [comment]
There is UPDATE user_forum_attributes SET status='verified' in _communicate
/main.py_ but I don't understand where is call of **connect_to_forum
/main.py** which is needed to make **INSERT INTO user_forum_attributes** or **DELETE FROM user_forum_attributes**

**Comment by Mikkdrasil** [comment]
@AKagitin i found a bug – when you type "связать аккаунты бота и форума" – and then, instead of typing the name you're pushing "в начало" – bot cracks. 
in "communicate" script in the function "manage_linking_to_forum" we'd need to add a case `if got-message == b_back_to_start` which will throws user to start. We also need to double-check that "bot_request_aft_usr_msg" is cleared for user in case of pushing back to start (it could be done by default – i don't recall how it's done in the code).

**Comment by Mikkdrasil** [comment]
#24 fixed the bug – "minimum objective" is completed.
next step is to upgrade functionality to "maximum objective"
